package tserviceClases;
// Generated 21/02/2015 11:39:05 AM by Hibernate Tools 4.3.1



import java.util.LinkedList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Calificacion generated by hbm2java
 */
@Entity
@Table(name="Calificacion"
    ,catalog="coswg2"
)
public class Calificacion  implements java.io.Serializable {


     private Integer id;
     private int rango;
     private String comentario;
     private int valor;
     private List<Oferta> ofertas = new LinkedList();

    public Calificacion() {
    }

	
    public Calificacion(int rango, String comentario, int valor) {
        this.rango = rango;
        this.comentario = comentario;
        this.valor = valor;
    }
    public Calificacion(int rango, String comentario, int valor, List<Oferta> ofertas) {
       this.rango = rango;
       this.comentario = comentario;
       this.valor = valor;
       this.ofertas = ofertas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Rango", nullable=false)
    public int getRango() {
        return this.rango;
    }
    
    public void setRango(int rango) {
        this.rango = rango;
    }

    
    @Column(name="Comentario", nullable=false, length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="Valor", nullable=false)
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="calificacion")
    public List<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(List<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


