package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="Categoria"
    ,catalog="coswg2"
)
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Oferta> ofertas = new HashSet(0);
     private Interes intereses;

    public Categoria() {
    }

	    
    public Categoria(String nombre) {
        this.nombre = nombre;
    }
    public Categoria(String nombre, Set<Oferta> ofertas, Interes intereses) {
       this.nombre = nombre;
       this.ofertas = ofertas;
       this.intereses = intereses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Oferta_has_Categoria", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="Categoria_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Oferta_id", nullable=false, updatable=false) })
    public Set<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set<Oferta> ofertas) {
        this.ofertas = ofertas;
    }
    
@OneToOne(fetch=FetchType.LAZY)
    public Interes getIntereses() {
        return this.intereses;
    }
    
    public void setIntereses(Interes intereses) {
        this.intereses = intereses;
    }




}


