package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExperienciaLaboral generated by hbm2java
 */
@Entity
@Table(name="Experiencia Laboral"
    ,catalog="coswg2"
)
public class ExperienciaLaboral  implements java.io.Serializable {


     private Integer id;
     private String entidad;
     private Date fechaActualizacion;
     private String comentario;
     private Set<Persona> personas = new HashSet(0);

    public ExperienciaLaboral() {
    }

	
    public ExperienciaLaboral(String entidad, Date fechaActualizacion, String comentario) {
        this.entidad = entidad;
        this.fechaActualizacion = fechaActualizacion;
        this.comentario = comentario;
    }
    public ExperienciaLaboral(String entidad, Date fechaActualizacion, String comentario, Set<Persona> personas) {
       this.entidad = entidad;
       this.fechaActualizacion = fechaActualizacion;
       this.comentario = comentario;
       this.personas = personas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Entidad", nullable=false, length=45)
    public String getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(String entidad) {
        this.entidad = entidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha Actualizacion", nullable=false, length=10)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    
    @Column(name="Comentario", nullable=false, length=45)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    
    @ManyToMany(fetch=FetchType.LAZY)
        @JoinTable(name="Persona_has_Experiencia Laboral", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="Experiencia Laboral_Id", nullable=false, updatable=false)}, inverseJoinColumns = { 
        @JoinColumn(name="Persona_Identificacion", nullable=false), 
        @JoinColumn(name="Persona_Tipo Identificacion",nullable=false) })
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


