package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Interes generated by hbm2java
 */
@Entity
@Table(name="Interes"
    ,catalog="coswg2"
)
public class Interes  implements java.io.Serializable {


     private Integer id;
     private String experiencia;
     //Mapear en BD
     private Categoria categoria;

    public Interes() {
    }
    
    public void setCategoria(Categoria categoria){
        this.categoria=categoria;
    }
    
    public Categoria getCategoria(){
        return this.categoria;
    }

    public Interes(String experiencia) {
       this.experiencia = experiencia;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="ExperienciaA�os", nullable=false, length=45)
    public String getExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(String experiencia) {
        this.experiencia = experiencia;
    }
}


