package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="Persona"
    ,catalog="coswg2"
)
@Inheritance(strategy = InheritanceType.JOINED)
public class Persona  implements java.io.Serializable {


     private PersonaId id;
     private HojaDeVida hojaDeVida;
     private String nombre;
     private Date fechaNacimiento;
     private List<ExperienciaLaboral> ExperienciaLaboral = (List<ExperienciaLaboral>) new HashSet(0);
     private List<Direcciones> direccioneses = (List<Direcciones>) new HashSet(0);
     private List<Correo> correos = (List<Correo>) new HashSet(0);

    public Persona() {
    }

	
    public Persona(PersonaId id, String nombre, Date fechaNacimiento, int hojaDeVidaId) {
        this.id = id;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Persona(PersonaId id, HojaDeVida hojaDeVida, String nombre, Date fechaNacimiento, List<ExperienciaLaboral> ExperienciaLaboral, List<Direcciones> direccioneses, List<Correo> correos) {
       this.id = id;
       this.hojaDeVida = hojaDeVida;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.ExperienciaLaboral = ExperienciaLaboral;
       this.direccioneses = direccioneses;
       this.correos = correos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identificacion", column=@Column(name="Identificacion", nullable=false) ), 
        @AttributeOverride(name="tipoIdentificacion", column=@Column(name="Tipo Identificacion", nullable=false, length=4) ) } )
    public PersonaId getId() {
        return this.id;
    }
    
    public void setId(PersonaId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Hoja de Vida_Id")
    public HojaDeVida getHojaDeVida() {
        return this.hojaDeVida;
    }
    
    public void setHojaDeVida(HojaDeVida hojaDeVida) {
        this.hojaDeVida = hojaDeVida;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha Nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Persona_has_Experiencia Laboral", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="Persona_Identificacion", nullable=false), 
        @JoinColumn(name="Persona_Tipo Identificacion",nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Experiencia Laboral_Id", nullable=false, updatable=false) })
    public List<ExperienciaLaboral> getExperienciaLaboral() {
        return this.ExperienciaLaboral;
    }
    
    public void setExperienciaLaboral(List<ExperienciaLaboral> ExperienciaLaboral) {
        this.ExperienciaLaboral = ExperienciaLaboral;
    }


@OneToMany(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Persona_Identificacion", referencedColumnName="Identificacion", nullable=false), 
        @JoinColumn(name="Persona_Tipo Identificacion", referencedColumnName="Tipo Identificacion", nullable=false) } )
    public List<Direcciones> getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(List<Direcciones> direccioneses) {
        this.direccioneses = direccioneses;
    }

@OneToMany(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Persona_Identificacion", referencedColumnName="Identificacion", nullable=false), 
        @JoinColumn(name="Persona_Tipo Identificacion", referencedColumnName="Tipo Identificacion", nullable=false) } )
    public List<Correo> getCorreos() {
        return this.correos;
    }
    
    public void setCorreos(List<Correo> correos) {
        this.correos = correos;
    }




}


