package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonaId generated by hbm2java
 */
@Embeddable
public class PersonaId  implements java.io.Serializable {


     private int identificacion;
     private String tipoIdentificacion;

    public PersonaId() {
    }

    public PersonaId(int identificacion, String tipoIdentificacion) {
       this.identificacion = identificacion;
       this.tipoIdentificacion = tipoIdentificacion;
    }
   


    @Column(name="Identificacion", nullable=false)
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }


    @Column(name="Tipo Identificacion", nullable=false, length=4)
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaId) ) return false;
		 PersonaId castOther = ( PersonaId ) other; 
         
		 return (this.getIdentificacion()==castOther.getIdentificacion())
 && ( (this.getTipoIdentificacion()==castOther.getTipoIdentificacion()) || ( this.getTipoIdentificacion()!=null && castOther.getTipoIdentificacion()!=null && this.getTipoIdentificacion().equals(castOther.getTipoIdentificacion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdentificacion();
         result = 37 * result + ( getTipoIdentificacion() == null ? 0 : this.getTipoIdentificacion().hashCode() );
         return result;
   }   


}


