package tserviceClases;
// Generated 17/02/2015 09:29:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Postulante generated by hbm2java
 */
@Entity
@Table(name="Postulante"
    ,catalog="coswg2"
)

public class Postulante extends Persona implements java.io.Serializable  {

     private int aspiracionSalarial;
     private List<Oferta> ofertas = (List<Oferta>) new HashSet(0);
     private List<Oferta> ofertas_1 = (List<Oferta>) new HashSet(0);
     private List<Interes> intereses = (List<Interes>) new HashSet(0);

    public Postulante() {
    }

	
    public Postulante( int aspiracionSalarial) {
        this.aspiracionSalarial = aspiracionSalarial;
    }
    public Postulante(int aspiracionSalarial, List<Oferta> ofertas, List<Oferta> ofertas_1, List<Interes> intereses) {
       this.aspiracionSalarial = aspiracionSalarial;
       this.ofertas = ofertas;
       this.ofertas_1 = ofertas_1;
       this.intereses = intereses;
    }
    
    @Column(name="AspiracionSalarial", nullable=false)
    public int getAspiracionSalarial() {
        return this.aspiracionSalarial;
    }
    
    public void setAspiracionSalarial(int aspiracionSalarial) {
        this.aspiracionSalarial = aspiracionSalarial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="postulante")
    public List<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(List<Oferta> ofertas) {
        this.ofertas = ofertas;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Oferta_has_Postulante", catalog="coswg2", joinColumns = { 
        @JoinColumn(name="Postulante_Persona_Identificacion", nullable=false), 
        @JoinColumn(name="Postulante_Persona_Tipo Identificacion",nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Oferta_id", nullable=false) })
    public List<Oferta> getOfertas_1() {
        return this.ofertas_1;
    }
    
    public void setOfertas_1(List<Oferta> ofertas_1) {
        this.ofertas_1 = ofertas_1;
    }

@OneToMany(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Postulante_Persona_Identificacion", referencedColumnName="Persona_Identificacion", nullable=false), 
        @JoinColumn(name="Postulante_Persona_Tipo Identificacion", referencedColumnName="Persona_Tipo Identificacion", nullable=false) } )
    public List<Interes> getIntereses() {
        return this.intereses;
    }
    
    public void setIntereses(List<Interes> intereses) {
        this.intereses = intereses;
    }




}


