package tserviceClases;
// Generated 21/02/2015 11:39:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Publicante generated by hbm2java
 */
@Entity
@Table(name="Publicante"
    ,catalog="coswg2"
)
public class Publicante extends Persona  implements java.io.Serializable {


     private String experiencia;
     private Date fechaUltimaLicecia;
     private List<Factura> facturas = new LinkedList();
     private List<Oferta> ofertas = new LinkedList();

    public Publicante() {
        super();
    }

	
    public Publicante(String experiencia, Date fechaUltimaLicecia) {
        super();
        this.experiencia = experiencia;
        this.fechaUltimaLicecia = fechaUltimaLicecia;
    }
    public Publicante(String experiencia, Date fechaUltimaLicecia, List<Factura> facturas, List<Oferta> ofertas) {
        super();
       this.experiencia = experiencia;
       this.fechaUltimaLicecia = fechaUltimaLicecia;
       this.facturas = facturas;
       this.ofertas = ofertas;
    }
   
   
    @Column(name="Experiencia", nullable=false, length=45)
    public String getExperiencia() {
        return this.experiencia;
    }
    
    public void setExperiencia(String experiencia) {
        this.experiencia = experiencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaUltimaLicecia", nullable=false, length=10)
    public Date getFechaUltimaLicecia() {
        return this.fechaUltimaLicecia;
    }
    
    public void setFechaUltimaLicecia(Date fechaUltimaLicecia) {
        this.fechaUltimaLicecia = fechaUltimaLicecia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publicante")
    public List<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(List<Factura> facturas) {
        this.facturas = facturas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="publicante")
    public List<Oferta> getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(List<Oferta> ofertas) {
        this.ofertas = ofertas;
    }




}


