package Entidades;


import java.util.HashSet;
import java.util.Set;


import java.util.HashSet;
import java.util.Set;


/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private Interes interes;
     private String nombre;
     private Set ofertas = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(Interes interes, String nombre) {
        this.interes = interes;
        this.nombre = nombre;
    }
    public Categoria(Interes interes, String nombre, Set ofertas) {
       this.interes = interes;
       this.nombre = nombre;
       this.ofertas = ofertas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Interes getInteres() {
        return this.interes;
    }
    
    public void setInteres(Interes interes) {
        this.interes = interes;
    }

    
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }
}
